// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { GeistSans } from 'geist/font/sans';

// import { Inter } from "next/font/google";
// import Sidebar from "./components/Sidebar";
// // import  Container  from "./Container/page";


// const inter = Inter({subsets: ["latin"]})

// export const metadata: Metadata = {
//   title: "G-Business",
//   description: "Generated by create next app",
// };


// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//     <body className={inter.className}>
//     <div className="flex">
//      <Sidebar clientUserId={""}/>
//       {/* <Container/> */}
//       <main className="flex-1">{children}</main>
//       </div>
     
     
      
//     </body>
//   </html>
//   );
// }

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ClientLayout from './ClientLayout';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'G-Business',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}